name: Node.js CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to production
        run: |
          npm install -g now
          now --prod
        env:
          NOW_TOKEN: ${{ secrets.NOW_TOKEN }}
